### ISSUE TITLE
Fails to open SVG fonts

### ISSUE THREAD

**Issue by evanrinehart** [diagrams/SVGFonts#15]
The lack of an IO type on the function openFont seems very silly. But besides that, after it lazily succeeds at openFont on for example this font http://suchanek.name/programs/fabiana/Fabiana/Fabiana-font.svg attempting to access any of the FontData results in the "head: empty list" crash. I'm very interested in nice text support for diagrams.

**Comment by tkvogt** [comment]
You are right about the IO type. I will change this. The bug maybe comes from SVGFonts expecting a file generated by fontforge. The parser is only tested on this input. If the parser fails somewhere there are empty lists. I am currently working on a parser for the full svg format which will be faster and more robust. Then I wanted to base SVGFonts on svg-diagrams.

**Comment by tkvogt** [comment]
Fixed. Same as #24 . Sorry for the procrastination. Issues don't go away by waiting :-)
