### ISSUE TITLE
Built-in lin2 font messes up "Pl"

### ISSUE THREAD

**Issue by duairc** [diagrams/SVGFonts#29]
Look at the output of this:

```haskell
import Data.Colour
import Diagrams
import Diagrams.Backend.SVG.CmdLine
import Graphics.SVGFonts
import Graphics.SVGFonts.ReadFont

pl :: PreparedFont Double -> Diagram B
pl font = textSVG_ (with {textFont = font}) "Pl" # lw none # fc black

main :: IO ()
main = lin2 >>= mainWith . pl
```

**Comment by byorgey** [comment]
Hmm, indeed, that is strange.  @tkvogt , any ideas?

**Comment by tkvogt** [comment]
LinLibertineCut.svg has some wrong kerning values (way too big) at the end of the file:
`<hkern g1="F,P,uni01A4,Rho,afii10034,uni1E1E,uni1E54,uni1E56"
	g2="exclam,question,b,h,k,l,thorn,hcircumflex,hbar,kcommaaccent,lacute,lcommaaccent,lcaron,ldot,lslash,uni0180,uni1E03,uni1E05,uni1E07,uni1E23,uni1E25,uni1E27,uni1E29,uni1E2B,uni1E31,uni1E33,uni1E35,uni1E37,uni1E39,uni1E3B,uni1E3D,exclamdbl"
	k="7696" />`
I deleted them. Until is uploaded to hackage use `lin` instead of `lin2`.
